'use client'

import { useState, useEffect, useCallback } from 'react'
import { toast } from 'sonner'
import {
  getVapidPublicKeyAction,
  subscribeToPushAction,
  unsubscribeFromPushAction,
  sendTestPushNotificationAction,
} from '@/app/(app)/notifications/push-actions'

function urlBase64ToUint8Array(base64String: string) {
  const padding = '='.repeat((4 - (base64String.length % 4)) % 4)
  const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/')
  const rawData = window.atob(base64)
  const outputArray = new Uint8Array(rawData.length)

  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i)
  }
  return outputArray
}

export function usePushNotifications() {
  const [isSupported, setIsSupported] = useState(false)
  const [permission, setPermission] = useState<NotificationPermission>('default')
  const [isSubscribed, setIsSubscribed] = useState(false)
  const [isLoading, setIsLoading] = useState(true)

  const checkSubscription = useCallback(async () => {
    if (typeof window === 'undefined') return
    const supported = 'serviceWorker' in navigator && 'PushManager' in window && 'Notification' in window
    setIsSupported(supported)

    if (!supported) {
      setIsLoading(false)
      return
    }

    setPermission(Notification.permission)

    try {
      const registration = await navigator.serviceWorker.register('/sw.js')
      const subscription = await registration.pushManager.getSubscription()
      setIsSubscribed(!!subscription)
    } catch (err) {
      console.error('Service worker check error:', err)
    } finally {
      setIsLoading(false)
    }
  }, [])

  useEffect(() => {
    checkSubscription()
  }, [checkSubscription])

  async function subscribe() {
    if (!isSupported) {
      toast.error('Push notifications are not supported by this browser.')
      return false
    }

    setIsLoading(true)
    try {
      let vapidKey = process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY
      if (!vapidKey) {
        const res = await getVapidPublicKeyAction()
        vapidKey = res.key ?? undefined
      }

      if (!vapidKey) {
        toast.error('VAPID public key is not configured in environment variables.')
        setIsLoading(false)
        return false
      }
      // Request browser permission
      const result = await Notification.requestPermission()
      setPermission(result)

      if (result !== 'granted') {
        toast.error('Notification permission was denied. Please allow notifications in browser settings.')
        setIsLoading(false)
        return false
      }

      const registration = await navigator.serviceWorker.ready
      let subscription = await registration.pushManager.getSubscription()

      if (!subscription) {
        subscription = await registration.pushManager.subscribe({
          userVisibleOnly: true,
          applicationServerKey: urlBase64ToUint8Array(vapidKey),
        })
      }

      const rawJson = subscription.toJSON()
      if (!rawJson.endpoint || !rawJson.keys?.p256dh || !rawJson.keys?.auth) {
        throw new Error('Incomplete push subscription generated by browser')
      }

      const serverRes = await subscribeToPushAction({
        endpoint: rawJson.endpoint,
        keys: {
          p256dh: rawJson.keys.p256dh,
          auth: rawJson.keys.auth,
        },
      })

      if (serverRes.error) {
        toast.error(serverRes.error)
        setIsLoading(false)
        return false
      }

      setIsSubscribed(true)
      toast.success('Device push notifications enabled!')
      return true
    } catch (err: any) {
      console.error('Error subscribing to push:', err)
      toast.error(err.message || 'Failed to enable push notifications')
      return false
    } finally {
      setIsLoading(false)
    }
  }

  async function unsubscribe() {
    if (!isSupported) return false

    setIsLoading(true)
    try {
      const registration = await navigator.serviceWorker.ready
      const subscription = await registration.pushManager.getSubscription()

      if (subscription) {
        const endpoint = subscription.endpoint
        await subscription.unsubscribe()
        await unsubscribeFromPushAction(endpoint)
      }

      setIsSubscribed(false)
      toast.success('Device push notifications disabled.')
      return true
    } catch (err: any) {
      console.error('Error unsubscribing from push:', err)
      toast.error(err.message || 'Failed to disable push notifications')
      return false
    } finally {
      setIsLoading(false)
    }
  }

  async function sendTest() {
    setIsLoading(true)
    try {
      const res = await sendTestPushNotificationAction()
      if (res.error) {
        toast.error(res.error)
      } else {
        toast.success('Test notification dispatched!')
      }
    } catch {
      toast.error('Failed to send test notification.')
    } finally {
      setIsLoading(false)
    }
  }

  return {
    isSupported,
    permission,
    isSubscribed,
    isLoading,
    subscribe,
    unsubscribe,
    sendTest,
  }
}
